// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniAppApi.Data;

#nullable disable

namespace MiniAppApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104183347_mig_2")]
    partial class mig_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniAppApi.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BannerImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BannerImageUrl = "https://example.com/images/tech-conference-2024.jpg",
                            Date = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An annual conference focusing on the latest in technology.",
                            Location = "San Francisco, CA",
                            OrganizerId = 1,
                            Title = "Tech Conference 2024"
                        },
                        new
                        {
                            Id = 2,
                            BannerImageUrl = "https://example.com/images/music-festival-2024.jpg",
                            Date = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A weekend of live music performances from various artists.",
                            Location = "Austin, TX",
                            OrganizerId = 2,
                            Title = "Music Festival"
                        },
                        new
                        {
                            Id = 3,
                            BannerImageUrl = "https://example.com/images/art-expo-2024.jpg",
                            Date = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An exhibition showcasing contemporary art from local artists.",
                            Location = "New York, NY",
                            OrganizerId = 1,
                            Title = "Art Expo"
                        });
                });

            modelBuilder.Entity("MiniAppApi.Models.Organizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Organizers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "samiralmammadli@gmail.com",
                            LogoUrl = "https://example.com/logos/tech_conferences.png",
                            Name = "Tech Conferences Inc.",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "",
                            LogoUrl = "https://example.com/logos/health_summit.png",
                            Name = "Health Summit Org.",
                            Phone = "987-654-3210"
                        });
                });

            modelBuilder.Entity("MiniAppApi.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            Price = 50.00m,
                            Type = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            EventId = 1,
                            Price = 150.00m,
                            Type = "VIP"
                        },
                        new
                        {
                            Id = 3,
                            EventId = 2,
                            Price = 40.00m,
                            Type = "Standard"
                        },
                        new
                        {
                            Id = 4,
                            EventId = 2,
                            Price = 70.00m,
                            Type = "Balcony"
                        });
                });

            modelBuilder.Entity("MiniAppApi.Models.Event", b =>
                {
                    b.HasOne("MiniAppApi.Models.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("MiniAppApi.Models.Ticket", b =>
                {
                    b.HasOne("MiniAppApi.Models.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MiniAppApi.Models.Event", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MiniAppApi.Models.Organizer", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
